version: "3.5" # Indica que versión del esquema de docker-compose estamos usando.

services:
    # Aqui dentro es donde definimos los contenedores
    mimysql: # Nombre DNS del contenedor dentro de la red de docker
        image: mysql:5.6.51 # IMAGEN 
        container_name: mimysql
        environment:
            - MYSQL_ROOT_PASSWORD=password                         # VARIABLES DE ENTORNO: Password usuario root \
            - MYSQL_DATABASE=curso                                 # VARIABLES DE ENTORNO: Nombre BBDD \
            - MYSQL_USER=usuario                                   # VARIABLES DE ENTORNO: Nombre usuario \
            - MYSQL_PASSWORD=password                              # VARIABLES DE ENTORNO: Password usuario \
        volumes:
            - ~/environment/datos/mysql:/var/lib/mysql             # VOLUMENES \
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 4 Gbs
                reservations:
                    cpus: 1
                    memory: 3 Gbs
        # docker-compose up --compatibility < Me permite usar esta sintaxis sin correr en swarm
        # Disponible en version 2 del esquema YAML de docker compose                    
        # mem_limit:
        # mem_reservation:
        # cpus:
    miwordpress:
        image: wordpress 
        container_name: miwp
        environment:
            - WORDPRESS_DB_HOST=mimysql
            - WORDPRESS_DB_NAME=curso
            - WORDPRESS_DB_USER=usuario
            - WORDPRESS_DB_PASSWORD=password
        ports:
            - 8081:80
        volumes:
            - ~/environment/datos/wp:/var/www/html

# 172.17.0.0/16    