FROM ubuntu:latest AS empaquetador

RUN apt-get update
RUN apt-get install git -y
RUN apt-get install maven -y

RUN git clone https://github.com/IvanciniGT/automatizacionTesting.git /tmp/proyecto
RUN cd /tmp/proyecto/mi-web-service && mvn package


FROM bitnami/tomcat:latest
COPY --from=empaquetador /tmp/proyecto/mi-web-service/target/mi-web-service.war /app
VOLUME ["/app"]