# Ordenes para generar la imagen nueva mia

# Imagen de la que parto
FROM fedora:latest      

    # Docker va a crear un contenedor con esta imagen.
    # En él va a ejecutar / Configurar lo que le pida...
    # Finalmente hará un commit de ese contenedor y le pondrá un tag
    # Docker va a mantener ese contenedor vivo mientras hacemos nuestro trabajo (configuramos nuestra nueva imagen)
    
# Ejecutar comandos en el contenedor temporal desde el que se creará la imagen
# RUN comando
RUN yum install nginx -y

# Configuraciones con valores por defecto

# Info para el que le interese